# Generated by Django 4.2.1 on 2023-05-11 20:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FriendRequests', '0003_rename_frndrequests_allrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allrequests',
            name='id',
        ),
        migrations.AddField(
            model_name='allrequests',
            name='request_user',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
