# Generated by Django 4.2.1 on 2023-05-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FriendRequests', '0004_remove_allrequests_id_allrequests_request_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allrequests',
            old_name='request_user',
            new_name='request_id',
        ),
    ]
